#33. Programa un código que permita contar el número de vocales de la siguiente frase: No hay mal que dure cien años
var1=str(input("Introduce la frase:(No hay mal que dure cien años)"))
a=var1.count("a")
print("El numero de vocales 'a' es",a)
e=var1.count("e")
print("El numero de vocales 'e' es",e)
i=var1.count("i")
print("El numero de vocales 'i' es",i)
o=var1.count("o")
print("El numero de vocales 'o' es",o)
u=var1.count("u")
print("El numero de vocales 'u' es",u)
